=== inspectIT/inspectIT/inspectit.server/src/main/external-resources/config/schema/configurationSchema.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <xs:element name="boolean-property" type="booleanProperty"/>

  <xs:element name="byte-property" type="byteProperty"/>

  <xs:element name="cmr-configuration" type="configuration"/>

  <xs:element name="group-property" type="groupedProperty"/>

  <xs:element name="isFullyQualifiedClassName" type="fullyQualifiedClassNameValidator"/>

  <xs:element name="isGreater" type="greaterValidator"/>

  <xs:element name="isGreaterOrEqual" type="greaterOrEqualValidator"/>

  <xs:element name="isLess" type="lessValidator"/>

  <xs:element name="isLessOrEqual" type="lessOrEqualValidator"/>

  <xs:element name="isNegative" type="negativeValidator"/>

  <xs:element name="isNotEmpty" type="notEmptyValidator"/>

  <xs:element name="isPercentage" type="percentageValidator"/>

  <xs:element name="isPositive" type="positiveValidator"/>

  <xs:element name="long-property" type="longProperty"/>

  <xs:element name="percentage-property" type="percentageProperty"/>

  <xs:element name="section" type="propertySection"/>

  <xs:element name="string-property" type="stringProperty"/>

  <xs:complexType name="abstractProperty" abstract="true">
    <xs:sequence/>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="description" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="singleProperty" abstract="true">
    <xs:complexContent>
      <xs:extension base="abstractProperty">
        <xs:sequence>
          <xs:element name="validators" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                  <xs:element ref="isLess"/>
                  <xs:element ref="isLessOrEqual"/>
                  <xs:element ref="isGreater"/>
                  <xs:element ref="isGreaterOrEqual"/>
                  <xs:element ref="isPercentage"/>
                  <xs:element ref="isPositive"/>
                  <xs:element ref="isNegative"/>
                  <xs:element ref="isFullyQualifiedClassName"/>
                  <xs:element ref="isNotEmpty"/>
                </xs:choice>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
        <xs:attribute name="logical-name" type="xs:string" use="required"/>
        <xs:attribute name="advanced" type="xs:boolean" use="required"/>
        <xs:attribute name="server-restart-required" type="xs:boolean" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="lessValidator">
    <xs:complexContent>
      <xs:extension base="abstractComparingValidator">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="abstractComparingValidator" abstract="true">
    <xs:sequence/>
    <xs:attribute name="property" type="xs:string"/>
    <xs:attribute name="than" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="lessOrEqualValidator">
    <xs:complexContent>
      <xs:extension base="abstractComparingValidator">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="greaterValidator">
    <xs:complexContent>
      <xs:extension base="abstractComparingValidator">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="greaterOrEqualValidator">
    <xs:complexContent>
      <xs:extension base="abstractComparingValidator">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="percentageValidator">
    <xs:complexContent>
      <xs:extension base="abstractSinglePropertyValidator">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="abstractSinglePropertyValidator" abstract="true">
    <xs:sequence/>
  </xs:complexType>

  <xs:complexType name="positiveValidator">
    <xs:complexContent>
      <xs:extension base="abstractSinglePropertyValidator">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="negativeValidator">
    <xs:complexContent>
      <xs:extension base="abstractSinglePropertyValidator">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="fullyQualifiedClassNameValidator">
    <xs:complexContent>
      <xs:extension base="abstractSinglePropertyValidator">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="notEmptyValidator">
    <xs:complexContent>
      <xs:extension base="abstractSinglePropertyValidator">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="stringProperty">
    <xs:complexContent>
      <xs:extension base="singleProperty">
        <xs:sequence/>
        <xs:attribute name="used-value" type="xs:string"/>
        <xs:attribute name="default-value" type="xs:string" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="longProperty">
    <xs:complexContent>
      <xs:extension base="singleProperty">
        <xs:sequence/>
        <xs:attribute name="used-value" type="xs:long"/>
        <xs:attribute name="default-value" type="xs:long" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="booleanProperty">
    <xs:complexContent>
      <xs:extension base="singleProperty">
        <xs:sequence/>
        <xs:attribute name="used-value" type="xs:boolean"/>
        <xs:attribute name="default-value" type="xs:boolean" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="percentageProperty">
    <xs:complexContent>
      <xs:extension base="singleProperty">
        <xs:sequence/>
        <xs:attribute name="used-value" type="xs:float"/>
        <xs:attribute name="default-value" type="xs:float" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="byteProperty">
    <xs:complexContent>
      <xs:extension base="singleProperty">
        <xs:sequence/>
        <xs:attribute name="used-value" type="xs:string"/>
        <xs:attribute name="default-value" type="xs:string" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="groupedProperty">
    <xs:complexContent>
      <xs:extension base="abstractProperty">
        <xs:sequence>
          <xs:element name="properties" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                  <xs:element ref="string-property"/>
                  <xs:element ref="long-property"/>
                  <xs:element ref="boolean-property"/>
                  <xs:element ref="percentage-property"/>
                  <xs:element ref="byte-property"/>
                </xs:choice>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element name="group-validators" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                  <xs:element ref="isLess"/>
                  <xs:element ref="isLessOrEqual"/>
                  <xs:element ref="isGreater"/>
                  <xs:element ref="isGreaterOrEqual"/>
                </xs:choice>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="configuration">
    <xs:sequence>
      <xs:element ref="section" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="propertySection">
    <xs:sequence>
      <xs:element name="properties" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
              <xs:element ref="string-property"/>
              <xs:element ref="long-property"/>
              <xs:element ref="boolean-property"/>
              <xs:element ref="percentage-property"/>
              <xs:element ref="byte-property"/>
              <xs:element ref="group-property"/>
            </xs:choice>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
  </xs:complexType>
</xs:schema>

=== inspectIT/inspectIT/CMR/config/default.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cmr-configuration xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/configurationSchema.xsd">
	<section name="Jetty">
		<properties>
			<long-property name="Port" default-value="8182" server-restart-required="true" logical-name="jetty.port" advanced="false"
				description="Port that will be opened for the communication to the inspectIT User interface.">
				<validators>
					<isPositive />
				</validators>
			</long-property>
			<long-property name="Graceful Shutdown Time" default-value="5000" server-restart-required="true" logical-name="jetty.graceful.shutdown.time" advanced="false"
				description='The "grace" period is the time the container will wait for requests currently inside the container to finish processing before shutting down.'>
				<validators>
					<isPositive />
					<isLessOrEqual than="60000" />
				</validators>
			</long-property>
			<group-property name="Threads" description="Defines size of the Jetty thread pool.">
				<properties>
					<long-property name="Min Threads" default-value="5" server-restart-required="true" logical-name="jetty.threads.min" advanced="false"
						description="The minimum thread number that will be in the thread pool for the incoming requests.">
						<validators>
							<isPositive />
							<isLessOrEqual than="50" />
						</validators>
					</long-property>
					<long-property name="Max Threads" default-value="20" server-restart-required="true" logical-name="jetty.threads.max" advanced="false"
						description="The maximum thread number that will be in the thread pool for the incoming requests.">
					</long-property>
				</properties>
				<group-validators>
					<isLess property="jetty.threads.min" than="jetty.threads.max" />
				</group-validators>
			</group-property>
		</properties>
	</section>
	<section name="JDBC">
		<properties>
			<string-property name="URL" default-value="jdbc:h2:db/inspectit;LOCK_MODE=0;CACHE_SIZE=131072;DB_CLOSE_ON_EXIT=FALSE" server-restart-required="true" logical-name="database.url"
				advanced="true" description="The JDBC URL pointing to the database.">
				<validators>
					<isNotEmpty />
				</validators>
			</string-property>
			<string-property name="Driver" default-value="org.h2.Driver" server-restart-required="true" logical-name="database.driver" advanced="true" description="The driver class to be used. ">
				<validators>
					<isFullyQualifiedClassName />
				</validators>
			</string-property>
			<string-property name="Username" default-value="inspectit" server-restart-required="true" logical-name="database.user" advanced="true" description="The username used to connect to the database.">
				<validators>
					<isNotEmpty />
				</validators>
			</string-property>
			<string-property name="Password" default-value="inspectit" server-restart-required="true" logical-name="database.password" advanced="true" description="The password used to connect to the database.">
				<validators>
					<isNotEmpty />
				</validators>
			</string-property>

		</properties>
	</section>
	<section name="Hibernate">
		<properties>
			<string-property name="Dialect" default-value="org.hibernate.dialect.H2Dialect" server-restart-required="true" logical-name="database.dialect" advanced="true"
				description="The Hibernate dialect to be used.">
				<validators>
					<isFullyQualifiedClassName />
				</validators>
			</string-property>
			<boolean-property name="Show SQL" default-value="false" server-restart-required="true" logical-name="database.showsql" advanced="true" description="If Hibernate should print the SQLs executed."></boolean-property>
			<boolean-property name="Format SQL" default-value="false" server-restart-required="true" logical-name="database.formatsql" advanced="true" description="If printed SQLs should be formated."></boolean-property>
		</properties>
	</section>
	<section name="General settings">
		<properties>
			<long-property name="Port" default-value="9070" server-restart-required="true" logical-name="cmr.port" advanced="false" description="The port used for communicating with agents.">
				<validators>
					<isPositive />
				</validators>
			</long-property>
			<boolean-property name="IP Based Registration" default-value="true" server-restart-required="false" logical-name="cmr.ipBasedAgentRegistration" advanced="false"
				description="Defines if the agents should be differently registered if they have different IP adresses."></boolean-property>
			<long-property name="Data Processing Threads" default-value="2" server-restart-required="false" logical-name="cmr.agentStorageServiceThreadCount" advanced="false"
				description="Number of threads that will process incoming data from the agent.">
				<validators>
					<isPositive />
					<isLessOrEqual than="10" />
				</validators>
			</long-property>
			<group-property name="Timer Data Aggregation" description="Defines properties for Timer data aggregation before saveing to the database.">
				<properties>
					<long-property name="Aggregation Period" default-value="10000" server-restart-required="false" logical-name="cmr.aggregationPeriod" advanced="true"
						description="Defines period in milliseconds for which all recieved data will be aggregated as one.">
						<validators>
							<isGreaterOrEqual than="1000" />
						</validators>
					</long-property>
					<long-property name="Max Elements" default-value="200" server-restart-required="false" logical-name="cmr.maxElements" advanced="true"
						description="Maximum number of elements aggregator will cache in memory while aggregating.">
						<validators>
							<isGreaterOrEqual than="20" />
						</validators>
					</long-property>
					<long-property name="Persist Period" default-value="60000" server-restart-required="false" logical-name="cmr.cacheCleanSleepingPeriod" advanced="true"
						description="Sleeping period in milliseconds for thread that is persisting the already aggregated objects.">
						<validators>
							<isGreaterOrEqual than="5000" />
						</validators>
					</long-property>
				</properties>
			</group-property>
		</properties>
	</section>
	<section name="Storage">
		<properties>
			<string-property name="Default Storage Folder" default-value="storage" server-restart-required="true" logical-name="storage.storageDefaultFolder" advanced="false"
				description="The name of the folder where all storage related data will be saved.">
				<validators>
					<isNotEmpty />
				</validators>
			</string-property>
			<byte-property name="Min GZIP Size" default-value="1MB" server-restart-required="true" logical-name="storage.minGzipSize" advanced="false"
				description="Min size in bytes for which the storage data will be served compressed." ></byte-property>
			<group-property name="Hard drive space protection" description="Defines properties that will protect against using all remaning space on the hard drive where CMR is running.">
				<properties>
					<byte-property name="Max Hard Drive Occupancy" default-value="0B" server-restart-required="false" logical-name="storage.maxHardDriveOccupancy" advanced="false"
						description="Amount of bytes that CMR can occupy on the Hard drive for the storage data. Zero value defines no limit, thus all available space will be used."></byte-property>
					<byte-property name="Warn on Bytes Left" default-value="1GB" server-restart-required="false" logical-name="storage.warnHardDriveByteLeft" advanced="false"
						description="Defines amount of bytes left to reach the maximum hard drive occupancy when user will be warned that the left space for storage data is low. ">
						<validators>
							<isPositive />
						</validators>
					</byte-property>
					<byte-property name="Stop Write on Bytes Left" default-value="100MB" server-restart-required="false" logical-name="storage.stopWriteHardDriveBytesLeft" advanced="false"
						description="Defines amount of bytes left to reach the maximum hard drive occupancy when all writes to the disk will be suspended.">
						<validators>
							<isPositive />
						</validators>
					</byte-property>
				</properties>
				<group-validators>
					<isLess property="storage.stopWriteHardDriveBytesLeft" than="storage.warnHardDriveByteLeft" />
				</group-validators>
			</group-property>
			<group-property name="Byte Buffer Pool" description="Defines properties for the pool of byte buffers that will be used during serialization and IO operations.">
				<properties>
					<byte-property name="Byte Buffer Size" default-value="1MB" server-restart-required="false" logical-name="storage.bufferSize" advanced="true" description="Capacity of the byte buffers in the pool.">
						<validators>
							<isGreaterOrEqual than="64KB" />
						</validators>
					</byte-property>
					<byte-property name="Pool Min Capacity" default-value="30MB" server-restart-required="false" logical-name="storage.bufferPoolMinCapacity" advanced="true"
						description="Minumum capacity of the pool. If this size is greater than the percentage of direct memory specified by Pool Min Direct Memory Occupancy, it will be decreased to that percentage.">
						<validators>
							<isGreaterOrEqual than="8MB" />
						</validators>
					</byte-property>
					<byte-property name="Pool Max Capacity" default-value="150MB" server-restart-required="false" logical-name="storage.bufferPoolMaxCapacity" advanced="true"
						description="Maximum capacity of the pool. If this size is greater than the percentage of direct memory specified by Pool Max Direct Memory Occupancy, it will be decreased to that percentage.">
					</byte-property>
					<percentage-property name="Pool Min Direct Memory Occupancy" default-value="30" server-restart-required="false" logical-name="storage.bufferPoolMinDirectMemoryOccupancy"
